sudo: required
dist: trusty
services:
  - docker
language: go
go:
  - 1.6
before_install:  
  - sudo apt-get update -yq
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -yq docker-engine
script:
  - make docker-test
  - if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      make docker-build-osd;
      docker login -e "${DOCKER_EMAIL}" -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
      docker push openstorage/osd;
    fi
