sudo: required
dist: trusty
services:
  - docker
language: go
go:
  - 1.6
before_install:  
  - sudo apt-get update -yq
  - sudo apt-get install -yq docker-engine
script:
  - make docker-test
after_success:
  - ./etc/travis/docker-push.bash
