---
osd:
  drivers:
      #nfs:
         #server: "localhost"
         #path: "/nfs"
      #btrfs:
         #home: "/var/lib/openstorage/btrfs"
#      aws:
#        aws_access_key_id: your_aws_access_key_id
#        aws_secret_access_key: your_aws_secret_access_key
